### ISSUE TITLE
Multiple version of service receipes

### ISSUE THREAD

**Issue by reidlai** [CloudifySource/cloudify-recipes#69]
Is there any way to have different version of service receipes?  Or can I create own receipes for latest service version?  E.g. CouchDB in your service receipes is 1.1.1 but the latest version is 1.3.0.  Thanks for your advice.

**Comment by tamirko** [comment]
In general, you can set different values in the properties file, but you need to make sure that you know what you're doing ( If you set the value to a newer version ) : 
Does such a version exist ? 
Is the download path correct ? 
Does the recipe in its current state do all the required steps for a proper installation and deployment ?

If the answer to one of the above is "no", then you should fix you current (local) recipe version and then use it 

HTH, 
Tamir.

**Comment by reidlai** [comment]
> Does the recipe in its current state do all the required steps for a proper installation and deployment ?

Agree and I really don't know how to prepare installation and deployment script.  Is there any document related to this topic?

**Comment by tamirko** [comment]
I refer you to their docs : http://couchdb.apache.org/

Good luck.

**Comment by barakm** [comment]
Closed, outdated.
